import XCTest
@testable import DesignSystem

/// The goldens below were generated by running the design file's reference
/// JavaScript engine (Paladala Expressive → 01 · Color engine / 02 · Shapes),
/// so a pass means the Swift port reproduces the design.
final class DSColorEngineTests: XCTestCase {
    private struct SchemeGolden {
        let seed: String
        let variant: DSVariant
        let dark: Bool
        let roles: [String: String]
    }

    private static let schemeGoldens: [SchemeGolden] = [
        SchemeGolden(seed: "#FF6194", variant: .vibrant, dark: false, roles: [
            "primary": "#BB005A",
            "onPrimary": "#FFFFFF",
            "primaryContainer": "#FFD9E1",
            "onPrimaryContainer": "#40001A",
            "secondary": "#855052",
            "secondaryContainer": "#FFDADA",
            "tertiary": "#885038",
            "tertiaryContainer": "#FFDBCC",
            "error": "#B91C25",
            "surface": "#FFF7F9",
            "surfaceContainer": "#F8EBED",
            "surfaceHighest": "#EDDFE2",
            "onSurface": "#22191B",
            "onSurfaceVariant": "#524346",
            "outline": "#837376",
            "outlineVariant": "#D4C2C6",
            "inverseSurface": "#382E30",
            "inversePrimary": "#FFB1C4",
        ]),
        SchemeGolden(seed: "#FF6194", variant: .vibrant, dark: true, roles: [
            "primary": "#FFB1C4",
            "onPrimary": "#66002E",
            "primaryContainer": "#8F0043",
            "onPrimaryContainer": "#FFD9E1",
            "secondary": "#F5B7B9",
            "secondaryContainer": "#6A383C",
            "tertiary": "#FBB79B",
            "tertiaryContainer": "#6D3922",
            "error": "#FFB4A9",
            "surface": "#1B1113",
            "surfaceContainer": "#261D1F",
            "surfaceHighest": "#3C3234",
            "onSurface": "#EDDFE2",
            "onSurfaceVariant": "#D4C2C6",
            "outline": "#9D8C90",
            "outlineVariant": "#524346",
            "inverseSurface": "#EDDFE2",
            "inversePrimary": "#BB005A",
        ]),
        SchemeGolden(seed: "#3D7BF7", variant: .expressive, dark: true, roles: [
            "primary": "#6FDAB6",
            "onPrimary": "#003829",
            "primaryContainer": "#00513D",
            "onPrimaryContainer": "#8CF6D2",
            "secondary": "#CDC0EC",
            "secondaryContainer": "#4B4166",
            "tertiary": "#FFB1C4",
            "tertiaryContainer": "#743045",
            "error": "#FFB4A9",
            "surface": "#141218",
            "surfaceContainer": "#201F24",
            "surfaceHighest": "#36343A",
            "onSurface": "#E4E1E9",
            "onSurfaceVariant": "#C8C5D0",
            "outline": "#928F99",
            "outlineVariant": "#48454E",
            "inverseSurface": "#E4E1E9",
            "inversePrimary": "#006C52",
        ]),
        SchemeGolden(seed: "#1FA37A", variant: .tonal, dark: false, roles: [
            "primary": "#006C4E",
            "onPrimary": "#FFFFFF",
            "primaryContainer": "#9BF4CF",
            "onPrimaryContainer": "#002115",
            "secondary": "#446557",
            "secondaryContainer": "#C5EBDA",
            "tertiary": "#126779",
            "tertiaryContainer": "#ADECFF",
            "error": "#B91C25",
            "surface": "#F4FBF8",
            "surfaceContainer": "#E8EFEC",
            "surfaceHighest": "#DDE4E1",
            "onSurface": "#181D1A",
            "onSurfaceVariant": "#404945",
            "outline": "#707975",
            "outlineVariant": "#BFC9C4",
            "inverseSurface": "#2C322F",
            "inversePrimary": "#7FD8B4",
        ]),
        SchemeGolden(seed: "#3D7BF7", variant: .fidelity, dark: false, roles: [
            "primary": "#005AC5",
            "onPrimary": "#FFFFFF",
            "primaryContainer": "#DEE0FF",
            "onPrimaryContainer": "#001A44",
            "secondary": "#495B9B",
            "secondaryContainer": "#DEE0FF",
            "tertiary": "#A03570",
            "tertiaryContainer": "#FFD8E9",
            "error": "#B91C25",
            "surface": "#F8F9FF",
            "surfaceContainer": "#EDEDF6",
            "surfaceHighest": "#E1E2EA",
            "onSurface": "#1B1B21",
            "onSurfaceVariant": "#454650",
            "outline": "#757681",
            "outlineVariant": "#C5C6D2",
            "inverseSurface": "#2F3036",
            "inversePrimary": "#BBC3FF",
        ]),
    ]

    private static let lchGoldens: [(String, Double, Double, Double)] = [
        ("#FF6194", 63.299, 64.274, 3.964),
        ("#3D7BF7", 53.892, 71.412, 288.334),
        ("#1FA37A", 59.790, 45.546, 165.049),
        ("#F2B705", 77.730, 80.121, 83.531),
        ("#5F6B7A", 44.736, 9.909, 264.324),
    ]


    private func role(_ name: String, in s: DSScheme) -> DSRGB? {
        switch name {
        case "primary": s.primary
        case "onPrimary": s.onPrimary
        case "primaryContainer": s.primaryContainer
        case "onPrimaryContainer": s.onPrimaryContainer
        case "secondary": s.secondary
        case "secondaryContainer": s.secondaryContainer
        case "tertiary": s.tertiary
        case "tertiaryContainer": s.tertiaryContainer
        case "error": s.error
        case "surface": s.surface
        case "surfaceContainer": s.surfaceContainer
        case "surfaceHighest": s.surfaceHighest
        case "onSurface": s.onSurface
        case "onSurfaceVariant": s.onSurfaceVariant
        case "outline": s.outline
        case "outlineVariant": s.outlineVariant
        case "inverseSurface": s.inverseSurface
        case "inversePrimary": s.inversePrimary
        default: nil
        }
    }

    private func assertClose(_ a: DSRGB, _ b: DSRGB, _ message: String, file: StaticString = #filePath, line: UInt = #line) {
        // Allow one step per channel: float rounding at .5 can differ by one.
        let ok = abs(Int(a.r) - Int(b.r)) <= 1 && abs(Int(a.g) - Int(b.g)) <= 1 && abs(Int(a.b) - Int(b.b)) <= 1
        XCTAssertTrue(ok, "\(message): got \(a.hex), expected \(b.hex)", file: file, line: line)
    }

    func test_schemesMatchReferenceEngine() throws {
        for g in Self.schemeGoldens {
            let seed = try XCTUnwrap(DSRGB(hex: g.seed))
            let scheme = DSScheme(seed: seed, variant: g.variant, dark: g.dark)
            for (name, hex) in g.roles {
                let got = try XCTUnwrap(role(name, in: scheme), "unknown role \(name)")
                let want = try XCTUnwrap(DSRGB(hex: hex))
                assertClose(got, want, "\(g.seed) \(g.variant) dark=\(g.dark) \(name)")
            }
        }
    }

    func test_lchMatchesReferenceEngine() throws {
        for (hex, l, c, h) in Self.lchGoldens {
            let lch = DSColorEngine.lch(try XCTUnwrap(DSRGB(hex: hex)))
            XCTAssertEqual(lch.l, l, accuracy: 0.01, hex)
            XCTAssertEqual(lch.c, c, accuracy: 0.01, hex)
            XCTAssertEqual(lch.h, h, accuracy: 0.01, hex)
        }
    }

    func test_toneExtremesAreBlackAndWhite() {
        XCTAssertEqual(DSColorEngine.tone(hue: 10, chroma: 50, tone: 0), .black)
        XCTAssertEqual(DSColorEngine.tone(hue: 10, chroma: 50, tone: 100), .white)
    }

    func test_toneTracksCielabLightness() {
        // Whatever chroma gets clipped, the result's L* stays on the requested tone.
        for t in [10.0, 30, 50, 70, 90] {
            let lch = DSColorEngine.lch(DSColorEngine.tone(hue: 4, chroma: 200, tone: t))
            XCTAssertEqual(lch.l, t, accuracy: 1.0)
        }
    }

    func test_hexParsing() {
        XCTAssertEqual(DSRGB(hex: "#FF6194"), .biliPink)
        XCTAssertEqual(DSRGB(hex: "f00"), DSRGB(r: 255, g: 0, b: 0))
        XCTAssertNil(DSRGB(hex: "#12345"))
        XCTAssertNil(DSRGB(hex: "zzzzzz"))
        XCTAssertEqual(DSRGB.biliPink.hex, "#FF6194")
    }

    func test_onRolesMeetTextContrast() {
        // Tone 40 on 100 and tone 80 on 20 are chosen to clear 4.5:1.
        for seed in DSTheme.seeds.map(\.rgb) {
            for dark in [false, true] {
                let s = DSScheme(seed: seed, variant: .vibrant, dark: dark)
                for (fg, bg) in [(s.onPrimary, s.primary), (s.onPrimaryContainer, s.primaryContainer),
                                 (s.onSurface, s.surface), (s.onSecondaryContainer, s.secondaryContainer)] {
                    XCTAssertGreaterThanOrEqual(Self.contrast(fg, bg), 4.5, "\(seed.hex) dark=\(dark)")
                }
            }
        }
    }

    func test_themeFallsBackToPinkForBadHex() {
        XCTAssertEqual(DSTheme(seedHex: "nope").seed, .biliPink)
    }

    private static func luminance(_ c: DSRGB) -> Double {
        func lin(_ v: UInt8) -> Double {
            let x = Double(v) / 255
            return x <= 0.04045 ? x / 12.92 : pow((x + 0.055) / 1.055, 2.4)
        }
        return 0.2126 * lin(c.r) + 0.7152 * lin(c.g) + 0.0722 * lin(c.b)
    }

    private static func contrast(_ a: DSRGB, _ b: DSRGB) -> Double {
        let la = luminance(a), lb = luminance(b)
        return (max(la, lb) + 0.05) / (min(la, lb) + 0.05)
    }
}

final class DSShapeTests: XCTestCase {
    /// Every 10th outline point (x, y in percent) from the reference engine.
    private static let shapeGoldens: [DSShape: [(Double, Double)]] = [
        .cookie9: [(50, 2.4), (72.6, 10.8), (91.2, 26.2), (100, 50), (91.2, 73.8), (72.6, 89.2), (50, 97.6), (25, 93.3), (8.8, 73.8), (4.8, 50), (8.8, 26.2), (25, 6.7)],
        .clover4: [(50, 8.5), (78.1, 1.3), (98.7, 21.9), (91.5, 50), (98.7, 78.1), (78.1, 98.7), (50, 91.5), (21.9, 98.7), (1.3, 78.1), (8.5, 50), (1.3, 21.9), (21.9, 1.3)],
        .triangle: [(50, 0), (70.4, 14.7), (79.8, 32.8), (90.8, 50), (93.3, 75), (70.4, 85.3), (50, 84.4), (29.6, 85.3), (6.7, 75), (9.2, 50), (20.2, 32.8), (29.6, 14.7)],
        .pill: [(50, 21), (66.7, 21), (89.2, 27.4), (100, 50), (89.2, 72.6), (66.7, 79), (50, 79), (33.3, 79), (10.8, 72.6), (0, 50), (10.8, 27.4), (33.3, 21)],
        .burst: [(50, 6.8), (71.6, 12.6), (87.4, 28.4), (93.2, 50), (87.4, 71.6), (71.6, 87.4), (50, 93.2), (28.4, 87.4), (12.6, 71.6), (6.8, 50), (12.6, 28.4), (28.4, 12.6)],
        .sunny: [(50, 1.7), (75.9, 5.2), (94.8, 24.1), (98.3, 50), (94.8, 75.9), (75.9, 94.8), (50, 98.3), (24.1, 94.8), (5.2, 75.9), (1.7, 50), (5.2, 24.1), (24.1, 5.2)],
    ]

    func test_everyShapeHasOneHundredTwentyPointsInTheUnitSquare() {
        for shape in DSShape.allCases {
            XCTAssertEqual(shape.points.count, DSShape.pointCount, shape.label)
            for p in shape.points {
                XCTAssertTrue((-0.0001...1.0001).contains(p.x) && (-0.0001...1.0001).contains(p.y), shape.label)
            }
        }
    }

    func test_shapesMatchReferenceOutlines() {
        for (shape, golden) in Self.shapeGoldens {
            let pts = shape.points
            for (i, g) in golden.enumerated() {
                let p = pts[i * 10]
                // The reference rounds to 0.1 %.
                XCTAssertEqual(Double(p.x) * 100, g.0, accuracy: 0.12, "\(shape.label) point \(i * 10) x")
                XCTAssertEqual(Double(p.y) * 100, g.1, accuracy: 0.12, "\(shape.label) point \(i * 10) y")
            }
        }
    }

    func test_polygonInterpolatesBetweenShapes() {
        let a = DSPolygon(.circle), b = DSPolygon(.burst)
        var mid = a.animatableData
        mid += (b.animatableData - a.animatableData).scaled(by: 0.5)
        XCTAssertEqual(mid.values.count, a.animatableData.values.count)
        XCTAssertEqual(mid.values[0], (a.animatableData.values[0] + b.animatableData.values[0]) / 2, accuracy: 1e-9)
    }

    func test_pointCloudZeroActsAsIdentity() {
        let cloud = DSPointCloud([1, 2, 3, 4])
        XCTAssertEqual(cloud + .zero, cloud)
        XCTAssertEqual(.zero + cloud, cloud)
        XCTAssertEqual(cloud - cloud, DSPointCloud([0, 0, 0, 0]))
    }

    func test_avatarShapeIsStablePerCreator() {
        XCTAssertEqual(DSShape.avatar(forID: "12345"), DSShape.avatar(forID: 12345))
        XCTAssertEqual(DSShape.avatar(forID: "碼農日常"), DSShape.avatar(forID: "碼農日常"))
        let shapes = Set((0..<200).map { DSShape.avatar(forID: $0) })
        XCTAssertEqual(shapes, Set(DSShape.avatarShapes), "ids should spread across every avatar polygon")
    }

    func test_loadingLoopHasSevenShapes() {
        XCTAssertEqual(DSShape.loadingLoop.count, 7)
    }
}
